disabled = false
languageCode = "zh-CN"
languageName = "中文"
weight = 1
title = "王二的自留地"

[params]
  displayName = "ZH"
  isoCode = "zh-CN"
  rtl = false
  dateFormat = "2006-01-02"
  description = "LLM / 摄影 / 写作 / 生活"

[params.author]
  name = "Wanger"
  image = "img/avatar.png"
  headline = "LLM Algorithm Engineer & Photographer"
  bio = "逆流而上的勇气，漏船载酒的运气"
  links = [
    { github = "https://github.com/Whiplashzeb" },
    { wechat = "javascript:void(0)" },
  ]
