[[main]]
  name = "写作"
  pageRef = "writing"
  weight = 10

[[main]]
  name = "LLM"
  pageRef = "llm"
  weight = 20

[[main]]
  name = "摄影"
  pageRef = "photography"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "about"
  weight = 40
